---
# main task for vlc

- name: vlc and dependencies are present
  become: "{{ should_be_root }}"

  block:
    - name: Install vlc via homebrew cask
      when: ansible_os_family in ["Darwin"]
      homebrew_cask:
        name: vlc
        state: present

    - name: Install vlc via apt (linux)
      when: ansible_os_family in ["Debian",  "Pop!_OS" ]
      apt:
        name: vlc

    - name: Install extra plugins for vlc (linux)
      when: ansible_os_family in ["Debian",  "Pop!_OS" ]
      apt:
        name: ["vlc-plugin-access-extra", "libbluray-bdj", "libdvdcss2"]
