---
# main task for neovim

- name: NEOVIM - bat is present
  become: "{{ should_be_root }}"

  block:
    - name: NEOVIM - neovim is present in debian
      apt:
        name: neovim
        state: present
        update_cache: yes
        dpkg_options: 'force-overwrite'
      when: ansible_os_family in ['Debian', 'Pop!_OS']
