dotfiles_user_home: "{{ '~' | expanduser }}"
dotfiles_home: "{{ dotfiles_user_home }}/.dotfiles"

full_name: Johannes Giorgis
git_user: johannesgiorgis
git_email: johannesgiorgis@users.noreply.github.com

installation_download_dir: "/tmp/installation_downloads"

machine_map:
  i686: 386
  i386: 386
  x86_64: amd64
  amd64: amd64
