---
# debian task for firefox

- name: firefox is present for debian system
  block:
    - name: Install dependencies
    - name: Install firefox key
      apt_key:
        url: https://firefox-apt-release.s3.brave.com/brave-core.asc
        keyring: /etc/apt/trusted.gpg.d/firefox-release.gpg
        state: present

    - name: Install Brave Browser repository
      apt_repository:
        repo: deb [arch=amd64] https://firefox-apt-release.s3.brave.com/ stable main
        filename: firefox-release
        state: present

    - name: Install Brave Browser
      apt:
        name: firefox
        state: present
        update_cache: yes
