---
- name: Add Conky Manager repository for 18.04 version
  apt_repository:
    repo: "ppa:mark-pcnetspec/conky-manager-pm9"
    state: present
    codename: trusty
  become: yes
  become_user: root
  become_method: sudo
  when: ansible_distribution_version == '18.04'

- name: Add Conky Manager repository for 20.04 version
  apt_repository:
    repo: "ppa:linuxmint-tr/araclar"
    state: present
  become: yes
  become_user: root
  become_method: sudo
  when: ansible_distribution_version == '20.04'

- name: Update repositories cache and install conky-manager package
  apt:
    name: "{{ item }}"
    update_cache: yes
  loop:
    - conky
    - conky-all
    - conky-manager
    - conky-manager-extra
  become: yes
  become_user: root
  become_method: sudo
