---
# debian tasks for obs-studio

- name: Add OBS Studio repository
  apt_repository:
    repo: "ppa:obsproject/obs-studio"
    state: present
    codename: trusty

- name: Update repositories cache and install obs-studio package
  apt:
    name: obs-studio
    update_cache: yes
